<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_We sent you the password reset link. Plea_a95c9a</name>
   <tag></tag>
   <elementGuidId>bb66ef72-8ed7-46bb-be39-4ec3be9e2f50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.authorization-page__body > p.forgot-password-form__desc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='checkEmailPage']/div[2]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c9340e16-6a34-41c2-b049-b2a42ec926cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>forgot-password-form__desc</value>
      <webElementGuid>66f4a1c4-76f1-4259-bcaa-6cd9e677189f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>We sent you the password reset link. Please, check your email.</value>
      <webElementGuid>176ceb9c-40ed-4758-a7ef-3c7cdd9b6de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkEmailPage&quot;)/div[@class=&quot;authorization-page__body&quot;]/p[@class=&quot;forgot-password-form__desc&quot;]</value>
      <webElementGuid>848e93b0-ef9f-46e1-a113-45b95aa5b3a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkEmailPage']/div[2]/p</value>
      <webElementGuid>78ba1c9e-08b3-4103-9e76-a7359f1921ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check your email'])[1]/following::p[1]</value>
      <webElementGuid>ef8e2e83-caef-4d2c-9700-01232712eec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::p[1]</value>
      <webElementGuid>f29a94e1-f8e3-4791-993d-b3aaba6a09f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Places to live'])[3]/preceding::p[1]</value>
      <webElementGuid>48f384e5-8526-4f10-8018-d89a01ac4bbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search for Places to Live'])[1]/preceding::p[1]</value>
      <webElementGuid>57a332a7-66d9-48e2-bb80-42e6a44a5bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='We sent you the password reset link. Please, check your email.']/parent::*</value>
      <webElementGuid>6ef95a73-9155-4f22-83f6-f8f352abb354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>72ad2613-3027-4583-9dbf-8ee9ab8cd860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'We sent you the password reset link. Please, check your email.' or . = 'We sent you the password reset link. Please, check your email.')]</value>
      <webElementGuid>a491ed0b-0deb-4b59-97e4-7af4b34964d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
